name: check-build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PYTHONUTF8: "1"

# only run one at a time per branch
concurrency:
  group: check-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: windows-latest
            python-version: '3.6'   # test fails due to UTF8 stuff
          - os: ubuntu-latest
            python-version: '3.6'   # not available in Ubuntu 22.04+
        include:
          - os: ubuntu-20.04
            python-version: '3.6'   # test Python 3.6 on older Ubuntu instead
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'macos-latest'
        name: Install Mac OS requirements
        run: brew install bash
      - if: matrix.os == 'windows-latest'
        name: Install Windows requirements
        run: choco install wget unzip
      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install .[dev]
          pip3 install .[ja]
          pip3 install .[ko]
      - name: Lint with Mypy
        run: mypy sacrebleu scripts test
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
      - name: Python pytest test suite
        run: python3 -m pytest
      - name: CLI bash test suite
        shell: bash
        run: ./test.sh
      - name: Build
        run: python3 setup.py sdist bdist_wheel
